### ISSUE TITLE
Implement vxgi on webgl?

### ISSUE THREAD

**Issue by FishOrBear** [gkjohnson/threejs-sandbox#10]

**Comment by gkjohnson** [comment]
Is there a specific question you have? I have not looked deeply into implementing VXGI and it could not be possible with the webgl APIs but I might give it a closer look at some point.

**Comment by FishOrBear** [comment]
Well, if only gi could be implemented in webgl.

**Comment by gkjohnson** [comment]
I may get around to trying it at some point but I put time into these projects in my free time so it will probably be awhile.
