### ISSUE TITLE
GTAOPass: Exclude helpers from render pass.

### ISSUE THREAD

**Issue by carstenschwede** [gkjohnson/threejs-sandbox#15]
First, thanks a lot for a many really awesome examples in your sandbox!

GTAO looks much better than SSAO in THREE.js and I wonder if you have an idea how I could exclude Helpers (e.g. CameraHelpers / GridLines / TransformControls / ...) from being included in the GTAOPass.

I'd like to render a room scene with GTAOPass but the additional helpers should be rendered as usual.
Would be great if you have an idea or could give me any pointers if this is possible.

**Comment by gkjohnson** [comment]
Thanks! Always happy to hear people using my work.

If you're looking for a better SSAO implementation than three.js' I recommend taking a look at the [postprocessing](https://github.com/vanruesc/postprocessing) package for three.js. The AO from GTAOPass does look nice but it can be performance intensive and not all of my projects in this repo are necessarily optimized.

Having said that I don't think the other SSAO pass will necessarily solve your problem -- the issue stems from the THREE.Line objects being rendered into the depth and normal buffers and therefore contributing to the AO effect. If the lines _weren't_ rendered to those buffers the AO effect would instead render on top of the lines which I don't think is what you're looking for, either. Your best bet I'd think would be rendering the objects that use GL_LINES _after_ all the post processing (or at least the AO) has run. That might be a bit tricky, though,

**Comment by carstenschwede** [comment]
Thanks for the quick response. I wasn't able to get vanruesc SSAO implementation to work with current THREE.js dev.
Based on your suggestion I took your GTAO and separated AO and non-AO objects in different scenes and rendered them in different passes, probably not a good idea in terms of performance but so far it looks nice. Devil is probably in the details. Now I just need a RTX 3090 :-D

<img width="1268" alt="Screenshot 2020-11-25 at 13 42 08" src="https://user-images.githubusercontent.com/234960/100229170-1ace7c00-2f24-11eb-97a9-20e543c7eb6a.png">

**Comment by carstenschwede** [comment]
Thanks for the quick response. I wasn't able to get vanruesc SSAO implementation to work with current THREE.js dev.
Based on your suggestion I took your GTAO and separated AO and non-AO objects in different scenes and rendered them in different passes, probably not a good idea in terms of performance but so far it looks nice. Devil is probably in the details. Now I just need a RTX 3090 :-D

<img width="1268" alt="Screenshot 2020-11-25 at 13 42 08" src="https://user-images.githubusercontent.com/234960/100229170-1ace7c00-2f24-11eb-97a9-20e543c7eb6a.png">

**Comment by Hoodgail** [comment]
@carstenschwede Doesn't make that force the helper's scene to render over the main scene?
