### ISSUE TITLE
BVH for InstancedMesh culling 

### ISSUE THREAD

**Issue by arpu** [gkjohnson/threejs-sandbox#17]
Hey,

not sure this is the right Place to ask, but hope to brainstorm some ideas
for my OpenWorld i use InstancedMesh with vertex wind animation,  next step is to implement some culling for this to reduce the triangles.

read some  forum threads like https://discourse.threejs.org/t/ridiculous-number-of-boxes/6862/11
the idea is to generate the frustum on cpu side with BVH and update the InstancedBuffer 

do you know any Technics how this could be done on GPU side too?

**Comment by gkjohnson** [comment]
Hey @arpu!

> do you know any Technics how this could be done on GPU side too?

I think this kind of culling is best done on the CPU given the capabilities of WebGL. With more modern graphics APIs using compute shaders you might be able to parallelize the culling a bit but it might wind up being more complicated than necessary.

Without knowing more about your current performance bottleneck it's hard to give too much advice but if you're definitely vertex bound and want to cull some of the instanced meshes I'd look into how long it would take to cull the instances individually without any kind of spatial index. If you're just dealing with a few hundred to a thousand items that might be fast enough. Like you mentioned you can then update the instance position buffer and draw range to draw the non-culled instances.

You could also split the sets of instances into "chunks" that can be automatically frustum culled by threejs. So if you have 1000 items you can spatially split them up into chunks of 50 instances each and then culling will only have to operate on the 20 instanced meshes. You could also look into doing the culling in a WebWorker, as well, but synchronizing the state between threads might add some complexity.

If neither of those simpler solutions is fast enough for what you're doing then I'd look into a static BVH or Octree.

**Comment by gkjohnson** [comment]
Gonna close this for now -- if you want to discuss more we can reopen. I'll be curious to hear what you wind up doing!
