### ISSUE TITLE
gtaoPass issue with version 118 and later

### ISSUE THREAD

**Issue by Lipacinp** [gkjohnson/threejs-sandbox#19]
Hello everyone,

I wanted to test the "gtaoPass" example and then integrate it into my project.

I managed to get it to work with the three.js version 114 to 117.
But in versions after 117, if one of the mesh has a diffuse color map, the error below is displayed:
![image](https://user-images.githubusercontent.com/83960969/117664865-88a0f400-b1a2-11eb-9396-4962b0ac1b60.png)

![image](https://user-images.githubusercontent.com/83960969/117668490-45e11b00-b1a6-11eb-8f28-a341e112a589.png)

Removing the diffuse map from all materials solves the problem.

I tried to solve the problem by looking in the code but I do not have the knowledge required to fully understand the functionality of "gtaoPass".

Does anyone have any idea where the problem might be?

**Comment by Lipacinp** [comment]
https://codesandbox.io/s/wispy-night-03sp4?file=/src/index.js

**Comment by Lipacinp** [comment]
https://codesandbox.io/s/festive-resonance-t9306

**Comment by gkjohnson** [comment]
Hi @Lipacinp thanks for the report. Unfortunately I don't have to bandwidth to provide help upgrading these experiments to new versions of three.js. Perhaps the three.js [migration guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide) can help or if you can narrow the problem down more specifically maybe the forum can help.
