### ISSUE TITLE
Motion blur

### ISSUE THREAD

**Issue by Hoodgail** [gkjohnson/threejs-sandbox#23]
The motion blur sandbox is perobject-motionblur  but is it possible to make a camera movement motion blur?

**Comment by gkjohnson** [comment]
If you enable the "cameraBlur" flag and set "speed" to 0 to disable all object movement you can see that the camera movement is taken into account in the blur:

![image](https://user-images.githubusercontent.com/734200/132144303-c6edc31b-92bc-4ce3-8ed5-42ec79b91157.png)

**Comment by Hoodgail** [comment]
I didn't notice this, thank you.
