### ISSUE TITLE
Motion Blur Bug on Skinning

### ISSUE THREAD

**Issue by jane-pm** [gkjohnson/threejs-sandbox#25]
motionBlurPass/webgl_postprocessing_perobjectmotionblur.html

Bug: Double skinned mesh object breaks velocity buffer.
Probability: 100%
OS: Windows/MacOSX
GPU: 3090 and M1
Browser: Chrome(93.0.4577.82), Electron(14.0.0), Edge(93.0.961.52)
Threejs Version: this repos version and r131.
Reproduce:

 - Just copy loading point.
 - Or load other skinned mesh object. (FBX/GLTF/PMX and so on)
 - Static mesh does not reproduce. Its just skinned mesh.

`

				loader.load( 'https://rawgit.com/mrdoob/three.js/r106/examples/models/fbx/Samba%20Dancing.fbx', res => {

					scene.add( res );
					res.scale.multiplyScalar( 0.05 );
					res.traverse( c => {

						if ( c.type === 'SkinnedMesh' ) {

							c.castShadow = true;
							c.receiveShadow = true;
							c.motionBlur = { expandGeometry: 0, interpolateGeometry: 0 }

						}

					});
					res.position.y = -5;
					mixer = new THREE.AnimationMixer( res );
					mixer.clipAction( res.animations[ 0 ] ).play();

				});

				loader.load( 'https://rawgit.com/mrdoob/three.js/r106/examples/models/fbx/Samba%20Dancing.fbx', res => {

					scene.add( res );
					res.scale.multiplyScalar( 0.05 );
					res.traverse( c => {

						if ( c.type === 'SkinnedMesh' ) {

							c.castShadow = true;
							c.receiveShadow = true;
							c.motionBlur = { expandGeometry: 0, interpolateGeometry: 0 }

						}

					});
					res.position.y = -5;
					mixer = new THREE.AnimationMixer( res );
					mixer.clipAction( res.animations[ 0 ] ).play();

				});

`

![test](https://user-images.githubusercontent.com/91010801/133925173-25efd59f-cd4c-493e-895e-8873996079ad.jpg)

**Comment by gkjohnson** [comment]
Hello! Thank you for the report. I work on these projects occasionally generally I don't maintain them or triage bug reports but if you'd like to make a PR to fix the issue I'd be happy to take a look and get that merged! And of course I'm happy to answer questions about the code to help get that moving. Let me know!

**Comment by jane-pm** [comment]
I was also tracking the MotionBlurPass.js implementation code for a bug fix.
I mentioned reproducing condition is simple.
That is "To exists two objects which are having skinning/skeleton in same scene."
Maybe the two objects are affecting each other and break velocity buffer due to something cache bug.

I turned off the follow codes, but no effect.


MotionBlurPass.js
```
 //let isSkinned = obj.type === 'SkinnedMesh' && obj.skeleton && obj.skeleton.bones && obj.skeleton.boneMatrices;
 let isSkinned = false;

		data.geometryMaterial.skinning = isSkinned;
		data.velocityMaterial.skinning = isSkinned;

```
I expected it to be a cache bug in the object bones of the MotionBlurPass.js implementation, but it doesn't seem to be the case. 

At first I was running it with Threejs-r131 in my repository, so I thought the glitch reason was a different version.
And I cloned your Master repository and just load two FBX object and reproduced it. It did not solve it.
Therefore I found that the version of Threejs was irrelevant, and my codes also.

That is what I did before reporting here. 
Perhaps the reason you didn't realize it during implementation was that there was only one Skinning object in the scene. 
My guess is threejs bug....maybe.
Its wondering behavior.

**Comment by gkjohnson** [comment]
I just took a quick look at adding a second animated skinned mesh and I see there is an issue. I'm not exactly sure what's causing it, though. Looking at the "Velocity" display you can see that the velocities for the problematic skinned mesh is what's causing issues while the "Geometry" buffer is rendering as expected.

It looks like the "prevBoneTexture" for the previous frame is not getting updated correctly but it requires more digging to understand exactly what's going on. It may be a three.js issue but I think making a simpler, more reductive demonstration of the problem in a JSFiddle would be a good first step to determining whether that's the case.

**Comment by jane-pm** [comment]
If I could create a simple reproduction code, it might be better to report it on the Threejs side instead of here.
I don't have much time too, so I'm going to slowly report and fix the problem. X(

**Comment by jane-pm** [comment]
Finally I found the glitch reason. 
It was just reference problem.

Object reference problem code in MotionBlurPass.js
```
			data = {

				lastUsedFrame: - 1,
				matrixWorld: obj.matrixWorld.clone(),
				geometryMaterial: new ShaderMaterial( GeometryShader ),  ← Here
				velocityMaterial: new ShaderMaterial( VelocityShader ),  ← Here
				boneMatrices: null,
				boneTexture: null,

			};
```
As it is, all the textures of the Skin Mesh object will be the same reference.
Threejs provides "THREE.UniformsUtils.clone()", and "UniformsUtils.merge()" and uniform must be "Deep Copy".

OutlineEffect.js from Threejs example lib.
```
		function createMaterial() {

			return new ShaderMaterial( {
				type: 'OutlineEffect',
				uniforms: UniformsUtils.merge( [ ← Here
					UniformsLib[ 'fog' ],
					UniformsLib[ 'displacementmap' ],
					uniformsOutline
				] ),
				vertexShader: vertexShader,
				fragmentShader: fragmentShader,
				side: BackSide
			} );

		}
```



I changed code as official style, and attach to ShaderMaterial.
```

			data = {

				lastUsedFrame: - 1,
				matrixWorld: obj.matrixWorld.clone(),
				geometryMaterial: new ShaderMaterial( {
					uniforms:UniformsUtils.clone(GeometryShader.uniforms),
					vertexShader:GeometryShader.vertexShader,
					fragmentShader:GeometryShader.fragmentShader,
				} ),
				velocityMaterial: new ShaderMaterial( {
					uniforms:UniformsUtils.clone(VelocityShader.uniforms),
					vertexShader:VelocityShader.vertexShader,
					fragmentShader:VelocityShader.fragmentShader,
				} ),
				boneMatrices: null,
				boneTexture: null,

			};
```
It works fine.

**Comment by gkjohnson** [comment]
Great! Thanks for the update. Would you like to make a PR with the changes so it's fixed for others, as well?

**Comment by jane-pm** [comment]
Yes, I'm already ready for PR, and I can do it if you made permission.
Other codes are also having compatible problem from the latest Threejs, so I would like to fix and PR little by little when I have time. ;)

**Comment by gkjohnson** [comment]
I'm happy to take any PRs if you'd like to get some of the demos up to date / fixed! Thanks!

> I can do it if you made permission

I shouldn't need to give permission for you to make a PR -- you need to make a fork of the repo, make a branch in your version, and then you can make a PR into this repo.

**Comment by jane-pm** [comment]
OK~ I'll do that later. ;)
