### ISSUE TITLE
Update all examples to run on latest three.js

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/threejs-sandbox#3]

**Comment by gkjohnson** [comment]
There are some quirks with the PCSS demo for some reason

**Comment by Bramichou** [comment]
Hello, any news regarding PCSS demo ? like the SoftShadow shader is not working at all in shaderchunk of three (In THREE 
R123)

**Comment by Bramichou** [comment]
@gkjohnson  i'm trying to run it on this latest version R123, but i can i have those errors , can you help me to implement it on that version ? or i need to get back into R94 version to get something working ? Your work looks amazing and i would like to try
 
![Capture d’écran 2020-12-24 à 23 01 27](https://user-images.githubusercontent.com/23286738/103107173-0d4c0500-463c-11eb-9d8c-3950d6919008.png)


Thank you so much !

**Comment by gkjohnson** [comment]
Hello @Bramichou! Thank you for your kind words. Maintaining these demos to keep up to date with the latest three.js version is a lot of work I unfortunately don't have the time for. Built-in shader modification and injection (like the PCSS example uses) is particularly difficult to keep up to date because they can change pretty unexpectedly and untraceably between versions.

I think it might be a bit difficult to get it working in the latest three.js version but there are some references in the [README](https://github.com/gkjohnson/threejs-sandbox/tree/master/pcss) that should hopefully help if you would like to understand how the effect works to dig into it.
