### ISSUE TITLE
No more updates?

### ISSUE THREAD

**Issue by aile1997** [gkjohnson/threejs-sandbox#32]
I was very surprised at how well this library worked, but it hasn't been updated in a while. I saw your example in the three.js example, but I think this one is even better

**Comment by aile1997** [comment]
MotionBlurPass screenSpaceReflectionsPass, sobel - the outline, shadow, these are great, why not appear in threejs example in?

**Comment by gkjohnson** [comment]
This project is not a library - it's a series of experiments and projects for people to learn from. Other projects are free to use the code but I have moved onto other work and never intended to maintain these effects. Feel free to contribute updates via PRs, though.
