### ISSUE TITLE
Conditional lines & SkinnedMesh

### ISSUE THREAD

**Issue by enyo** [gkjohnson/threejs-sandbox#34]
I have looked, tried and implemented a dozen solutions to get outlines, but none look as amazing as your conditional lines.

I would really like to use it in my project, but unfortunately it doesn't work for skinned meshes.

Do you think it would be possible to get it to work with a skinned mesh? I'm quite new to three.js and shader development, but if you say that it would be possible, I'd try to figure it out.

Any input would be much appreciated.

**Comment by gkjohnson** [comment]
It's possible but it's non trivial. I would start by getting basic line geometry working with skinning and then you can apply this to the conditional lines. I recommend asking for help at the three.js forums for more help:

https://discourse.threejs.org/

**Comment by enyo** [comment]
@gkjohnson thank you
